"use client"

// import { createContext, useReducer } from "react";
import "./globals.css";
// import { reducer } from "../reducer/reducerGeneral";
import { UserProvider } from "@/context/UserProvider";
import { NavBar } from "@/components/NavBar";

// export const metadata = {
//   title: "Next JWT",
//   description: "Generated by create next app",
// };

// export const contexto = createContext();

// const initialState = {
//   contador: 0
// }

export default function RootLayout({ children }) {

  // const [state, dispatch] = useReducer(reducer, initialState);

  return (
    <html lang="en">
      <UserProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
