import { UserProvider } from "@/context/UserProvider";
import { NavBar } from "@/components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Next JWT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <UserProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
